version: '2'
services:
  server_prod:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - 9015:9015
    environment:
      - CONFIG_PATH=/src/examples/numbers/config.docker.json
      - WORKFLOWS_PATH=/src/examples/numbers/workflows
    depends_on:
      - redis_prod
  monitor_prod:
    build:
      context: monitor
      dockerfile: Dockerfile.production
    volumes:
      - /src/monitor/node_modules
      - /src/monitor/bower_components
    depends_on:
      - server_prod
    ports:
      - 9000:9000
  worker_prod:
    build:
      context: deployment
      dockerfile: Dockerfile.production
    environment:
      - POLIGLO_SERVER_URL=http://server:9015
      - WORKERS_PATHS=/src/examples/numbers/workers/
      - SUPERVISOR_LOG_PATH=/tmp/poliglo_supervisor_logs
    depends_on:
      - server_prod
      - redis_prod
  redis_prod:
    image: redis:3.2
